server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/userdb
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
